### ISSUE TITLE
Source code locations are lost

### ISSUE THREAD

**Issue by khinsen** [jeapostrophe/rackunit-chk#3]
I used this macro happily for a while, until a change to my code made a large number of tests fail. Now I find myself facing a long list of messages such as

```
--------------------
FAILURE
name:       check-false
location:   (#<path:/Users/hinsen/Library/Racket/6.4/pkgs/rackunit-chk/rackunit/chk.rkt> 47 9 1429 43)
expression: (ru:check-false (first (res:values-vs xv)))
params:     (#t)

--------------------
```

with no idea of which tests actually failed.

**Comment by jeapostrophe** [comment]
Yes, various things about the way that rackunit works makes it very difficult to get it to use the source locations of macro applications that expand to rackunit. That's one of the reasons I wrote

https://github.com/jeapostrophe/chk

Its syntax is almost identical, so my guess is that you could just trivially switch over if you want. I can also give it a second look if there's something I missed the first few times trying to get source locations in rackunit-chk

**Comment by khinsen** [comment]
Your new implementation looks both simpler and nicer, so I will happily transition to it. I am not particularly attached to `rackunit`. Whatever works with `raco test` is good for me!
